### ISSUE TITLE
Feature request - A function to group elements in a Non-empty list

### ISSUE THREAD

**Issue by emmanuelrosa** [mgold/elm-nonempty-list#3]
The elm-community/lists-extra package features a function called `groupWhile` which is handy for going from a `List a` to a `List (List a)` with *like* elements being grouped together into sub-lists; where *like-ness* is determined by a function of signature `a -> a -> Bool`.

I would like to see such a function implemented for non-empty lists. I've implemented the function as shown below. As to it's correctness... I suppose that's debatable :)

## An implementation

Here's my idea for an implementation. Note, the like the equivalent function in List.Extras, this one may produce unexpected results if the list is not sorted first.

```elm
import List.Nonempty as NE exposing (..)
import Html exposing (text)


{-| Groups the elements in the non-empty list using the predicate.
NOTICE: You may want to sort the list first.

    import List.Nonempty as NE

    [1, 1, 2, 3, 3]
        |> NE.fromList
        |> Maybe.map (groupWhile (==))
        |> Maybe.withDefault []

        -- Result is [[1, 1], [2], [3, 3]]
-}
groupWhile : (a -> a -> Bool) -> Nonempty a -> Nonempty (Nonempty a)
groupWhile predicate list =
    let
        seed : Nonempty (Nonempty a)
        seed =
            head list
                |> fromElement
                |> fromElement

        folder : a -> Nonempty (Nonempty a) -> Nonempty (Nonempty a)
        folder current groups =
            let
                group : Nonempty a
                group =
                    head groups
            in
                if all (predicate current) group then
                    Nonempty (fromElement current |> append group) (tail groups)
                else
                    (fromElement current) ::: groups
    in
        case list of
            Nonempty a [] ->
                fromElement list

            Nonempty a (x :: xs) ->
                foldl folder seed (Nonempty x xs)
                    |> NE.reverse
```

## Implementation description

Because the list is not empty, the grouping process begins by creating the first group using the head of the list. If the list only contains one element, then the group is returned, and that's the end of it. Otherwise, the tail --which is guaranteed to have at least one element-- is turned into a non-empty list and the folding begins.

If the predicate signifies that *adjacent* elements are alike, then they are grouped together.

Finally, because new groups are added to the front of the list, the final step is to reverse the list so that the original ordering is preserved; though nested into sub-lists.

**Comment by mgold** [comment]
It seems like you could do this relying on the implementation of `List.Extra.groupBy`. For instance,
`NE.toList >> List.Extra.groupWhile predicate >> List.map NE.fromList >> List.filterMap identity >> NE.fromList`. (This isn't quite right since it returns a `Maybe (Nonempty a)` but you get the idea.) At the very minimum it would make a good fuzz test to compare it versus your implementation.

Why don't you give this a go in a PR with tests so we can be more confident about correctness?

**Comment by emmanuelrosa** [comment]
Initially I converted the non-empty list to a list in order to use groupWhile from List.Extra, but as you mentioned, it introduces the maybe.

I'll work on a PR. Should this go in an *extra* module, or in the one you already have?

**Comment by mgold** [comment]
> Initially I converted the non-empty list to a list in order to use groupWhile from List.Extra, but as you mentioned, it introduces the maybe.

There are [ways around](https://github.com/mgold/elm-nonempty-list/blob/b0eb0e55f2e1481deaf7f6d65eed7c2affaae0d9/src/List/Nonempty.elm#L359-L360) that, but it would need to be very well-tested.

> Should this go in an extra module, or in the one you already have?

I'm willing to add it to the main library.
