### ISSUE TITLE
order of operands to `append`

### ISSUE THREAD

**Issue by norpan** [mgold/elm-nonempty-list#7]
The documentation for `append` does not specify which list is appended to which. Normally in Elm, we put the data structure being operated on last, so that we can do
```
list1
    |> List.Nonempty.append list2
```
Since this seems not to be the case here, it should perhaps be documented.

**Comment by mgold** [comment]
It works exactly the same as `(++)` for normal lists. It appends them in argument order.

>we put the data structure being operated on last

That only makes sense when you have one large data structure. Append has two.

**Comment by norpan** [comment]
Well, `(++)` is infix, so it's a bit different. The operation is called `append`, not `prepend`, so there is a sense of one data structure being appended by something. I'm just saying the documentation is not totally clear, so a clarification could be in order.
